I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 831, in script
    wen "Oh, Mutter! Ein Kleid?"
Exception: Sayer 'wen' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 831, in script
    wen "Oh, Mutter! Ein Kleid?"
  File "C:\Users\vladi\Downloads\renpy-8.3.4-sdk.7z\renpy-8.3.4-sdk\renpy\ast.py", line 2579, in execute
    Say.execute(self)
  File "C:\Users\vladi\Downloads\renpy-8.3.4-sdk.7z\renpy-8.3.4-sdk\renpy\ast.py", line 581, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\vladi\Downloads\renpy-8.3.4-sdk.7z\renpy-8.3.4-sdk\renpy\ast.py", line 470, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'wen' is not defined.

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.4.24120703
FruehlingsErwachen 1.0
Mon Dec 16 18:05:05 2024
